version: "3"
services:

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
      - 9000:9000
    volumes:
      - .:/var/www/html/
    depends_on:
      - mysql
    links:
      - mysql


  nginx:
    image: nginx:alpine
    depends_on:
      - php-fpm
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - .:/var/www/html/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf


  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    volumes:
      - ./docker/data:/var/lib/mysql
#      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8888:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
    depends_on:
      - mysql
    

    